version: "3"

services:
  web:
    build: "."
    environment:
      RAILS_ENV: development
    command: bin/rails s -b 0.0.0.0
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: postgres:10.5
    environment:
      POSTGRES_DB: app_development
